class Product {
  final String imageUrl;
  final String productName;
  final String sellerName;
  final double price;
  final int discount;
  final double rating;
  final String category;
  Product({
    required this.imageUrl,
    required this.productName,
    required this.sellerName,
    required this.price,
    required this.discount,
    required this.rating,
    required this.category,
  });
}

final List<Product> products = [
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Evening Dress',
    sellerName: 'Dorothy Perkins',
    price: 29.99,
    category: 'Dresses',
    discount: 15,
    rating: 4.5,
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Casual Dress',
    sellerName: 'Zara',
    price: 49.99,
    discount: 20,
    rating: 4.7,
    category: 'Crop Tops',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Crop Top',
    sellerName: 'Forever 21',
    price: 19.99,
    discount: 10,
    rating: 4.2,
    category: 'Sleeveless',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Sleeveless Blouse',
    sellerName: 'H&M',
    price: 24.99,
    discount: 5,
    rating: 4.0,
    category: 'Skirts',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Denim Skirt',
    sellerName: 'Levi\'s',
    price: 34.99,
    discount: 15,
    rating: 4.3,
    category: 'Jeans',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Classic Jeans',
    sellerName: 'Wrangler',
    price: 39.99,
    discount: 10,
    rating: 4.1,
    category: 'Blouses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Chiffon Blouse',
    sellerName: 'Mango',
    price: 29.99,
    discount: 12,
    rating: 4.4,
    category: 'Blouses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Summer Skirt',
    sellerName: 'GAP',
    price: 25.99,
    discount: 8,
    rating: 4.0,
    category: 'Skirts',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Party Dress',
    sellerName: 'Bershka',
    price: 59.99,
    discount: 18,
    rating: 4.8,
    category: 'Dresses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Office Shirt',
    sellerName: 'Uniqlo',
    price: 19.99,
    discount: 5,
    rating: 4.0,
    category: 'Jeans',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Hoodie',
    sellerName: 'Nike',
    price: 49.99,
    discount: 15,
    rating: 4.6,
    category: 'Blouses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Joggers',
    sellerName: 'Adidas',
    price: 39.99,
    discount: 12,
    rating: 4.3,
    category: 'Blouses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Blazer',
    sellerName: 'Zara',
    price: 69.99,
    discount: 10,
    rating: 4.5,
    category: 'Dresses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Polo Shirt',
    sellerName: 'Ralph Lauren',
    price: 44.99,
    discount: 5,
    rating: 4.4,
    category: 'Crop Tops',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Formal Pants',
    sellerName: 'Hugo Boss',
    price: 59.99,
    discount: 18,
    rating: 4.5,
    category: 'Sleeveless',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Sweater',
    sellerName: 'Uniqlo',
    price: 29.99,
    discount: 8,
    rating: 4.2,
    category: 'Skirts',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Leather Jacket',
    sellerName: 'Levi\'s',
    price: 89.99,
    discount: 25,
    rating: 4.7,
    category: 'Jeans',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Pullover',
    sellerName: 'Zara',
    price: 39.99,
    discount: 12,
    rating: 4.3,
    category: 'Blouses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Long Coat',
    sellerName: 'Mango',
    price: 109.99,
    discount: 20,
    rating: 4.8,
    category: 'Sleeveless',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Sports Shorts',
    sellerName: 'Nike',
    price: 24.99,
    discount: 5,
    rating: 4.3,
    category: 'Crop Tops',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Yoga Pants',
    sellerName: 'Lululemon',
    price: 49.99,
    discount: 12,
    rating: 4.6,
    category: 'Dresses',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Silk Scarf',
    sellerName: 'Gucci',
    price: 79.99,
    discount: 15,
    rating: 4.7,
    category: 'Sleeveless',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Track Jacket',
    sellerName: 'Adidas',
    price: 59.99,
    discount: 20,
    rating: 4.4,
    category: 'Crop Tops',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Sneakers',
    sellerName: 'Puma',
    price: 64.99,
    discount: 10,
    rating: 4.5,
    category: 'Skirts',
  ),
  Product(
    imageUrl: 'https://m.media-amazon.com/images/I/61Bkqv9e4cL._AC_UY1000_.jpg',
    productName: 'Graphic Tee',
    sellerName: 'H&M',
    price: 14.99,
    discount: 5,
    rating: 4.1,
    category: 'Jeans',
  ),
];
